---
- name: Ensure pip is installed by apk.
  apk:
    name: py-pip
    update_cache: yes
    state: latest

- name: Ensure virtualenv is installed by apk.
  apk:
    name: py-virtualenv
    update_cache: yes

- name: Purge apk cache.
  command: rm -rf /var/cache/apk/*
  when: ansible_connection == 'docker'    