---
- name: Ensure required packages are installed.
  apk:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - python
    - python-devel

- name: Ensure pip is installed by apk.
  apk:
    name: py-pip
    state: latest

- name: Ensure virtualenv is installed by apk.
  apk:
    name: py-virtualenv

- name: Purge apk cache.
  command: rm -rf /var/cache/apk/*
  when: ansible_connection == 'docker'    